@Ecommerce.Api_HostAddress = http://localhost:5112

GET {{Ecommerce.Api_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{Ecommerce.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
